repos:
  - repo: https://github.com/efrecon/pre-commit-hook-lxml
    rev: v0.1.2
    hooks:
      - id: format-xml
        args:
          - --indent=2
          - --endings=unix
          - --write
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: forbid-crlf
      - id: remove-crlf
  - repo: https://github.com/comkieffer/xml-linter-hook.git
    rev: 1.0.0
    hooks:
      - id: xmllint
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0 # Use the ref you want to point at
    hooks:
      - id: check-byte-order-marker
      - id: check-merge-conflict
      - id: check-xml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.1.0" # Use the sha or tag you want to point at
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@3.2.5
          - "@prettier/plugin-xml@3.4.1"
