name: Create Release

on:
  push:
    tags:
      - "*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Zip DataCustom folder
        run: |
          zip -r DataCustom.zip DataCustom
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: DataCustom.zip
